# Generated by Django 3.2.7 on 2021-09-22 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.IntegerField(default=-1, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('default_value', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('category_id', models.PositiveSmallIntegerField(choices=[(0, 'Shoulders'), (1, 'Back'), (2, 'Biceps'), (3, 'Triceps'), (4, 'Chest'), (5, 'Core'), (6, 'Gluteus'), (7, 'Quadriceps'), (8, 'Hamstring'), (9, 'Cardio'), (10, 'Lumbar'), (11, 'Grip')], default=1)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'N1'), (1, 'N2'), (2, 'RX'), (3, 'RX+')], default=0)),
                ('url', models.URLField()),
                ('is_metabolic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('exercise_ids', models.CharField(blank=True, max_length=512, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('exercise_repetitions', models.CharField(blank=True, max_length=512, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('rounds', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('percentages', models.CharField(max_length=512, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
